# Generated by Django 2.0.3 on 2018-03-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
